### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by AdrianAgache** [JammingJammerIsJammingToJam/space-trading-sim#11]
**DISCLAMER: This issue isn't very important but if you have name ideas pls contribute**

Simply just give your ideas for game names in the comments

**Comment by JammingJammerIsJammingToJam** [comment]
Anomaly #31

**Comment by AdrianAgache** [comment]
Nice name

**Comment by AdrianAgache** [comment]
I'll wait for more ideas before closing the issue

**Comment by AdrianAgache** [comment]
ye its now closed
