### ISSUE TITLE
Implementation of test-spread.py with next steps

### ISSUE THREAD

**Issue by JammingJammerIsJammingToJam** [JammingJammerIsJammingToJam/space-trading-sim#5]
Create a system so that each system has planets with generated names and different goods to buy. These planets need to save to a file.

**Comment by XSHORXHALIARO** [comment]
Each moon is (planet name)-(number). Each planet is (star)-(position). Hence we only need code for the following:
Names for stars (systems are (star name)-system)
The amount of planets in each system
The number of moons in each system.
We could have creative names but this is **way** easier.

**Comment by AdrianAgache** [comment]
For planet names should we make random 3 letter combinations?

**Comment by AdrianAgache** [comment]
oops i didnt mean to close it

**Comment by AdrianAgache** [comment]
and should we make a list of different resources and label each planet of having 2-3 different main resources

**Comment by JammingJammerIsJammingToJam** [comment]
I have created a script to add 4 planets to each system (4 is more conveinient than any other number as it matches with the numbers of lines of text per system.
